services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
    # volumes:
    #   - ./webapp:/opt/webapp
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - PORT=8080
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
